development:
  adapter: mysql2
  database: feast20013_dev
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: feast20013_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: feast20013
  pool: 5
  timeout: 5000
  user: root
